
#Lab 2: Data Preprocessing

This notebook provides hands-on practice for data preprocessing concepts.

## 1. Setup & Dataset Overview

In [6]:
# importing necessary libraries and creating dummy data with NaN values
import pandas as pd
import numpy as np

data = {
    "Age": [20, 21, 21, 22, np.nan, 23, 21],
    "BMI": [22.5, 27.8, 27.8, 30.1, np.nan, np.nan, 27.8],
    "StudyHours": [5, 7, 7, 3, 6, 8, 7],
    "FinalScore": [65, 78, 78, 55, 70, 85, 78]
}

df = pd.DataFrame(data)
df

    Age   BMI  StudyHours  FinalScore
0  20.0  22.5           5          65
1  21.0  27.8           7          78
2  21.0  27.8           7          78
3  22.0  30.1           3          55
4   NaN   NaN           6          70
5  23.0   NaN           8          85
6  21.0  27.8           7          78

## 2. Data Cleaning

In [7]:
# What this code is checking?
df.isnull().sum()

Age           1
BMI           2
StudyHours    0
FinalScore    0
dtype: int64

In [9]:
# missing value imputation
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["BMI"] = df["BMI"].fillna(df["BMI"].median())
df = df.drop_duplicates()
df

         Age   BMI  StudyHours  FinalScore
0  20.000000  22.5           5          65
1  21.000000  27.8           7          78
3  22.000000  30.1           3          55
4  21.333333  27.8           6          70
5  23.000000  27.8           8          85

## 3. Normalization

In [10]:
# Normalization examples using Min Max and Z-score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[["Age", "BMI", "StudyHours"]] = scaler.fit_transform(
    df[["Age", "BMI", "StudyHours"]]
)
df_minmax

        Age       BMI  StudyHours  FinalScore
0  0.000000  0.000000         0.4          65
1  0.333333  0.697368         0.8          78
3  0.666667  1.000000         0.0          55
4  0.444444  0.697368         0.6          70
5  1.000000  0.697368         1.0          85

In [11]:
scaler = StandardScaler()
df_zscore = df.copy()
df_zscore[["Age", "BMI", "StudyHours"]] = scaler.fit_transform(
    df[["Age", "BMI", "StudyHours"]]
)
df_zscore

        Age       BMI  StudyHours  FinalScore
0 -1.463418 -1.870152   -0.464991          65
1 -0.465633  0.238743    0.697486          78
3  0.532152  1.153923   -1.627467          55
4 -0.133038  0.238743    0.116248          70
5  1.529937  0.238743    1.278724          85

## 4. Data Transformation & Feature Engineering

In [13]:
# Transform: discretization
df.loc[:, "BMI_Category"] = pd.cut(
    df.loc[:, "BMI"],
    bins=[0, 18.5, 25, 30, 100],
    labels=["Underweight", "Normal", "Overweight", "Obese"]
)

# Feature engineering: construction
df.loc[:, "StudyEfficiency"] = df.loc[:, "FinalScore"] / df.loc[:, "StudyHours"]

df

         Age   BMI  StudyHours  FinalScore BMI_Category  StudyEfficiency
0  20.000000  22.5           5          65       Normal        13.000000
1  21.000000  27.8           7          78   Overweight        11.142857
3  22.000000  30.1           3          55        Obese        18.333333
4  21.333333  27.8           6          70   Overweight        11.666667
5  23.000000  27.8           8          85   Overweight        10.625000

## 5. Dimentionality Reduction

In [14]:
# Principal component analysis (PCA)
from sklearn.decomposition import PCA

features = df[["Age", "BMI", "StudyHours", "FinalScore"]]
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(features)
reduced_data

array([[ -5.64616078,  -4.93188791],
       [  7.46878572,   0.44610038],
       [-15.85358962,   2.91439102],
       [ -0.57071857,   0.52196978],
       [ 14.60168324,   1.04942674]])

## 6. Reflection

- Why is normalization important?
- When should PCA be applied?
- How would preprocessing differ for text or image data?